#!/usr/bin/env bash
# Install nginx web server and add a custom nginx response header.

apt-get update
apt-get intall -y nginx

mkdir -p /var/www/html
touch /var/html/index.html
echo "Hello World!" > /var/html/index.html
touch /var/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     add_header X-Served-By $HOSTNAME;
     root   /var/www/html;
     index  index.html index.htm;

     location /redirect_me {
         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }
}" > /etc/nginx/sites-available/default

service nginx restart
