#!/usr/bin/env bash
# Installs HAProxy version 2.7 on lb-01 server.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
apt-get update
apt-get install -y haproxy=2.7.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

server_config=\
"
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend myfrontend
    bind *:80
    mode http
    default_backend mybackend_servers
backend mybackend_servers
    balance roundrobin
    server 155852-web-01 52.91.203.47:80 check
    server 155852-web-02 54.89.134.41:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start

