#!/usr/bin/env bash
# Installs HAProxy version 2.7 on lb-01 server.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
apt-get update
apt-get install -y haproxy=2.7.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect  5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend myfrontend
    bind *:80
    mode http
    default_backend mybackend_servers
backend mybackend_servers
    balance roundrobin
    server 155852-web-01 52.91.203.47:80 check
    server 155852-web-02 54.89.134.41:80 check

listen lb-01
    bind 0.0.0.0:80
    mode http
    balance roundrobin
    server 155852-web-01 52.91.203.47:80 check
    server 155852-web-02 54.89.134.41:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

